### ISSUE TITLE
Fail to Login in UI - Unauthorized requests to velero-api 

### ISSUE THREAD

**Issue by MuriloCouceiro** [seriohub/velero-api#35]
Hello, 

I'm getting these 401's in the velero-api module, which blocks me from logging in the velero-ui.

![image](https://github.com/user-attachments/assets/7a61b6f8-518d-44c8-b995-ab8ed7ea00f1)

I'm deploying both with helm charts (velero v6.7.0 and vui v0.1.13). 

Any ideas of what might be causing this?

here are my vui values: 

```yaml
global:
  veleroNamespace: velero
  kubernetesClusterDomain: cluster.local

apiConfig: 
  awsAccessKeyId: velero
  awsSecretAccessKey: velero123
  origins1: '<url>'
  debugLevel: info
  apiEnableDocumentation: 1

uiConfig:
  # -- Url to http velero-api project
  nextPublicVeleroApiUrl: <url>
  # -- Url to ws velero-api project
  nextPublicVeleroApiWs: <url>

uiNp:
  enabled: false

uiIngress:
  # -- Enable or disable ingress
  enabled: true
  # -- Ingress class name
  ingressClassName: nginx
  metadata: 
    annotations: 
      cert-manager.io/cluster-issuer: issuer
      nginx.ingress.kubernetes.io/proxy-read-timeout: '3600'
      nginx.ingress.kubernetes.io/proxy-send-timeout: '3600'
  host: <url>
  spec:
    tls: 
    -.....
 
```

**Comment by davideserio** [comment]
Hi,
Can you try to authorize in swagger? 
You can find the swagger user interface at https://\<your-velero-domain>/api/docs

**Comment by MuriloCouceiro** [comment]
Hi, 
thanks for getting back!

I found nothing wrong in the logs, just a 200 for /api/docs

However in the interface I get the following error:
![image](https://github.com/user-attachments/assets/23b1c8af-eeb1-4b1b-83b1-dddc383252ec)

**Comment by davideserio** [comment]
Hi,

This error has been fixed with the latest Helm version, v0.1.14, which includes the updated API v0.18. 
Can you update Helm and verify if you can authenticate in the Swagger interface?

**Comment by MuriloCouceiro** [comment]
Thanks, I have updated the chart version and can now use the swagger interface!

Yet, the same thing happens. I've logged in with swagger and tried the /api/v1/setup/version endpoint but got a 401 again

**Login:**

![image](https://github.com/user-attachments/assets/75aaa0b9-66fd-4201-beeb-707bcdd0790d)

![image](https://github.com/user-attachments/assets/8d589236-e3a0-4b42-9d56-fe75be5d5fea)

**Request:** 

![image](https://github.com/user-attachments/assets/386cabde-19fb-4cfd-89fb-f7befb7db465)

**Comment by davideserio** [comment]
Do you use the subdirectory?

The swagger interface uses the following url format
```
https://<\your-velero-domain\>/<subdirectory>/api/docs
```
or

```
https://<\your-velero-domain\>/api/docs
```

**Comment by MuriloCouceiro** [comment]
It uses 

```
https://<\your-velero-domain\>/api/docs
```

**Comment by davideserio** [comment]
With reference to your values override can you try the following configuration?

```
global:
  veleroNamespace: velero
  kubernetesClusterDomain: cluster.local

apiConfig: 
  awsAccessKeyId: velero
  awsSecretAccessKey: velero123
  origins1: '*'
  debugLevel: debug
  apiEnableDocumentation: 1

#uiConfig:
# # -- Url to http velero-api project
#  nextPublicVeleroApiUrl: <url>
#  # -- Url to ws velero-api project
#  nextPublicVeleroApiWs: <url>

uiNp:
  enabled: false

uiIngress:
  # -- Enable or disable ingress
  enabled: true
  # -- Ingress class name
  ingressClassName: nginx
  metadata: 
    annotations: 
      cert-manager.io/cluster-issuer: issuer
      nginx.ingress.kubernetes.io/proxy-read-timeout: '3600'
      nginx.ingress.kubernetes.io/proxy-send-timeout: '3600'
  spec:
    tls: 
      - hosts:
         - <url-domain>
         .....
```

Next, can you try authenticating in Swagger again? 
Also, on the login page, at the bottom left, there is a button to display more diagnostic information. Can you check it?
