### ISSUE TITLE
Could not validate credentials

### ISSUE THREAD

**Issue by mm3906078** [seriohub/velero-api#37]
**Issue with Login and Authorization**

Hi guys,

I'm having an issue with the login process for my application. I can access the `/api/docs`, and in the authorizations section, when I enter the wrong username and password, I get an error as expected. However, when I enter the correct username and password, I'm unable to access the API endpoints.

Here's an example request:

```bash
curl -X 'GET' \
  'https://###.###.com/api/v1/users/me/info' \
  -H 'accept: application/json' \
  -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTcyNTcxNDg2NH0.qsqq6mR9TdLyIKsIWebnOPNH2Xs73N3ZfbiSYwgR_-4'
```

The response I'm getting is:

```json
{
  "detail": "Could not validate credentials"
}
```

I'm also using Traefik for my ingress configuration:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vui-ingress
  namespace: velero-ui
  annotations:
    traefik.ingress.kubernetes.io/custom-response-headers: |
      Access-Control-Allow-Origin: *
      Access-Control-Allow-Methods: *
      Access-Control-Allow-Headers: *
      Access-Control-Expose-Headers: *
    traefik.ingress.kubernetes.io/websocket: 'true'
spec:
  ingressClassName: traefik
  rules:
    - host: ###.###.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vui-ui
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: vui-api
                port:
                  number: 80
          - path: /ws
            pathType: Prefix
            backend:
              service:
                name: vui-api
                port:
                  number: 80
  tls:
    - hosts:
        - ###.###.com
```

**Debugging Data:**

```bash
# Agent State Manager Report**

- Backend info
  - app_name: **velero-api**;
  - helm_app_version: **0.1.14**;
  - helm_version: **0.1.15**;
  - helm_api: **0.1.18**;
  - helm_ui: **0.1.16**;
  - api_release_version: **0.1.18**;
  - helm_watchdog: **0.1.6**;
- UI URL: **https://###.###.###**
- API URL: **https://###.###.###/api**
- K8s Health
  - cluster online: **true**
  - nodes:
    - total: **11**;
    - in error: **0**;
- API Origins
  - *;
- Architecture: **amd64**
- Watchdog: **alive**
- Compatibility: **true**
- Boolean State
  - getUiURL: **true**;
  - getApiURL: **true**;
  - checkApiReacheable: **true**;
  - getArchitecture: **true**;
  - getOrigins: **true**;
  - validateOrigins: **true**;
  - getWatchdogInfo: **true**;
  - getClusterHealth: **true**;
  - getUiApiVerCompatibility: **true**;
```

Any insights on why the correct credentials aren’t allowing access to the API endpoints but incorrect ones throw an error? It seems to be a token validation issue, but I’m unsure how to proceed with the debugging.

Thanks in advance!
